#!/bin/bash

output=$(ssh -A $1 exit 2>&1)
echo "$output"
if [[ $output == *"Permission denied (publickey)."* ]]
then
  echo "yinit may be required to log in."
  yinit
  ssh -A $1
else
  ssh -A $1
fi
